#ifndef FRONTEND_H
#define FRONTEND_H

/* Embedded HTML page with live metrics (Sample Rate, Age, RTT) */
static const char *s_html =
"<!DOCTYPE html><html><head><title>Picoscope</title>"
"<meta charset='utf-8'>"
"<style>"
"body{font-family:monospace;background:#0a0a0a;color:#0f0;margin:20px}"
"h2{margin:0 0 20px 0}"
"#info{background:#1a1a1a;border:1px solid #333;padding:14px;margin-bottom:10px}"
".row{display:flex;gap:30px;margin:4px 0}"
".label{color:#888;min-width:150px}"
".value{color:#0f0;font-weight:bold}"
"canvas{border:1px solid #333;background:#000;display:block}"
"#status{color:#888;margin-top:6px;font-size:12px;text-align:center}"
".error{color:#f44}"
"</style></head><body>"
"<h2>PICOSCOPE</h2>"
"<div id='info'>"
"<div class='row'><span class='label'>Vmin:</span><span id='vmin' class='value'>---</span></div>"
"<div class='row'><span class='label'>Vmax:</span><span id='vmax' class='value'>---</span></div>"
"<div class='row'><span class='label'>Vavg:</span><span id='vavg' class='value'>---</span></div>"
"<div class='row'><span class='label'>Vpp:</span><span id='vpp' class='value'>---</span></div>"
"<div class='row'><span class='label'>Sample Rate:</span><span id='sps' class='value'>---</span></div>"
"<div class='row'><span class='label'>Data Age:</span><span id='age' class='value'>---</span></div>"
"<div class='row'><span class='label'>Latency RTT:</span><span id='rtt' class='value'>---</span></div>"
"<div class='row'><span class='label'>Update Rate:</span><span id='fps' class='value'>--- Hz</span></div>"
"</div>"
"<canvas id='scope' width='800' height='300'></canvas>"
"<div id='status'>Connecting...</div>"
"<script>"
"const c=document.getElementById('scope'),x=c.getContext('2d'),W=c.width,H=c.height;"
"let last=Date.now(),frames=0,prevTs=null,ws=null;"
"function grid(){x.strokeStyle='#1a1a1a';x.lineWidth=1;"
"for(let i=0;i<=10;i++){x.beginPath();x.moveTo(0,i*H/10);x.lineTo(W,i*H/10);x.stroke();"
"x.beginPath();x.moveTo(i*W/10,0);x.lineTo(i*W/10,H);x.stroke();}}"
"function draw(s){x.fillStyle='#000';x.fillRect(0,0,W,H);grid();"
"x.strokeStyle='#0f0';x.lineWidth=2;x.beginPath();"
"for(let i=0;i<s.length;i++){const xx=i/(s.length-1)*W,yy=H-(s[i]/4095)*H;"
"if(i===0)x.moveTo(xx,yy);else x.lineTo(xx,yy);}x.stroke();}"
"function sendPing(){if(ws&&ws.readyState===1){ws.send('ping '+Date.now());}}"
"setInterval(sendPing,2000);"
"function connect(){ws=new WebSocket('ws://'+location.hostname+'/ws');"
"ws.binaryType='arraybuffer';"
"ws.onopen=()=>{document.getElementById('status').textContent='Connected'};"
"ws.onclose=()=>{document.getElementById('status').textContent='Disconnected';document.getElementById('status').className='error';setTimeout(connect,2000)};"
"ws.onerror=()=>{document.getElementById('status').textContent='Error';document.getElementById('status').className='error'};"
"ws.onmessage=e=>{"
" if(typeof e.data==='string'){"
"  const s=e.data;"
"  if(s.startsWith('ping ')){const t=parseInt(s.slice(5));if(!isNaN(t)){const r=Date.now()-t;document.getElementById('rtt').textContent=r+' ms';}}"
"  return;"
" }"
" const v=new DataView(e.data),ts=v.getUint32(0,true),age=v.getUint32(4,true),sc=v.getUint32(8,true),"
" vmin=v.getFloat32(12,true),vmax=v.getFloat32(16,true),vavg=v.getFloat32(20,true),"
" s=new Uint16Array(e.data,24,256);"
" draw(s);"
" document.getElementById('vmin').textContent=vmin.toFixed(3)+' V';"
" document.getElementById('vmax').textContent=vmax.toFixed(3)+' V';"
" document.getElementById('vavg').textContent=vavg.toFixed(3)+' V';"
" document.getElementById('vpp').textContent=(vmax-vmin).toFixed(3)+' V';"
" document.getElementById('age').textContent=age+' ms';"
" if(prevTs!==null){const dt=(ts-prevTs)/1000; if(dt>0){const sps=sc/dt; document.getElementById('sps').textContent=(sps/1000).toFixed(1)+' kSPS';}}"
" prevTs=ts;"
" frames++;const now=Date.now();if(now-last>=1000){document.getElementById('fps').textContent=frames+' Hz';frames=0;last=now;}"
"};}connect();"
"</script></body></html>";

#endif 