#include "frontend.h"

/* Embedded HTML page with live metrics AND interactive controls */
const char frontend_index_html[] =
"<!DOCTYPE html><html><head><title>Picoscope</title>"
"<meta charset='utf-8'>"
"<style>"
"body{font-family:monospace;background:#0a0a0a;color:#0f0;margin:20px}"
"h2{margin:0 0 20px 0}"
"#info{background:#1a1a1a;border:1px solid #333;padding:14px;margin-bottom:10px}"
".row{display:flex;gap:30px;margin:4px 0}"
".label{color:#888;min-width:150px}"
".value{color:#0f0;font-weight:bold}"
"canvas{border:1px solid #333;background:#000;display:block}"
"#status{color:#888;margin-top:6px;font-size:12px;text-align:center}"
".error{color:#f44}"
"#controls{background:#1a1a1a;border:1px solid #333;padding:14px;margin-bottom:10px}"
".panel{margin-bottom:15px}"
"h3{color:#0f0;font-size:14px;margin:0 0 8px 0}"
"label{display:block;margin:5px 0;color:#888}"
".inline-controls{display:flex;gap:15px;align-items:center;flex-wrap:wrap}"
".inline-controls label{margin:0}"
"select,input,button{background:#000;color:#0f0;border:1px solid #333;padding:4px;font-family:monospace}"
"button{cursor:pointer;padding:8px 16px}"
"button:hover{background:#1a1a1a}"
"</style></head><body>"
"<h2>PICOSCOPE</h2>"
"<div id='info'>"
"<div class='row'><span class='label'>Vmin:</span><span id='vmin' class='value'>---</span></div>"
"<div class='row'><span class='label'>Vmax:</span><span id='vmax' class='value'>---</span></div>"
"<div class='row'><span class='label'>Vavg:</span><span id='vavg' class='value'>---</span></div>"
"<div class='row'><span class='label'>Vpp:</span><span id='vpp' class='value'>---</span></div>"
"<div class='row'><span class='label'>Sample Rate:</span><span id='sps' class='value'>---</span></div>"
"<div class='row'><span class='label'>Data Age:</span><span id='age' class='value'>---</span></div>"
"<div class='row'><span class='label'>Latency RTT:</span><span id='rtt' class='value'>---</span></div>"
"<div class='row'><span class='label'>Update Rate:</span><span id='fps' class='value'>--- Hz</span></div>"
"</div>"
"<div id='controls'>"
"  <div class='panel'>"
"    <h3>TRIGGER</h3>"
"    <div class='inline-controls'>"
"      <label>Mode: "
"        <select id='trigMode'>"
"          <option value='0'>AUTO</option>"
"          <option value='1'>NORMAL</option>"
"          <option value='2'>NONE</option>"
"        </select>"
"      </label>"
"      <label>Edge: "
"        <select id='trigEdge'>"
"          <option value='0'>RISING</option>"
"          <option value='1'>FALLING</option>"
"        </select>"
"      </label>"
"      <label>Level: <input type='range' id='trigLevel' min='0' max='3.3' step='0.01' value='1.65'> "
"        <span id='trigLevelVal'>1.65V</span>"
"      </label>"
"    </div>"
"  </div>"
"  <div class='panel'>"
"    <h3>TIMEBASE</h3>"
"    <div class='inline-controls'>"
"      <label>Time/Div: "
"        <select id='timeDiv'>"
"          <option value='0.00001'>10us</option>"
"          <option value='0.0001'>100us</option>"
"          <option value='0.001'>1ms</option>"
"          <option value='0.01' selected>10ms</option>"
"          <option value='0.1'>100ms</option>"
"        </select>"
"      </label>"
"      <button id='runStop'>STOP</button>"
"    </div>"
"  </div>"
"</div>"
"<canvas id='c' width='800' height='400'></canvas>"
"<div id='status'>Connecting...</div>"
"<script>"
"const canvas=document.getElementById('c'),ctx=canvas.getContext('2d');"
"let ws,running=true;"
"let pingTimer=null,lastFrameMs=0,fpsAvg=0;"
"const rttEl=document.getElementById('rtt');"
"const fpsEl=document.getElementById('fps');"
"function connect(){"
"  ws=new WebSocket('ws://'+location.host+'/ws');"
"  ws.binaryType='arraybuffer';"
"  ws.onopen=()=>{"
"    document.getElementById('status').textContent='Connected';"
"    if(pingTimer) clearInterval(pingTimer);"
"    pingTimer=setInterval(()=>{"
"      if(ws&&ws.readyState===1){ ws.send('ping '+Date.now()); }"
"    },1000);"
"  };"
"  ws.onclose=()=>{"
"    document.getElementById('status').textContent='Disconnected';"
"    if(pingTimer){ clearInterval(pingTimer); pingTimer=null; }"
"    setTimeout(connect,2000);"
"  };"
"  ws.onerror=()=>document.getElementById('status').textContent='Error';"
"  ws.onmessage=e=>{"
"    if(typeof e.data==='string'){"
"      if(e.data.startsWith('ping ')){"
"        const t=parseInt(e.data.slice(5))||0;"
"        if(t>0){ rttEl.textContent=(Date.now()-t)+'ms'; }"
"        return;"
"      }"
"      try{const r=JSON.parse(e.data);console.log('Response:',r);}catch(_){ }"
"      return;"
"    }"
"    const now=performance.now();"
"    if(lastFrameMs>0){"
"      const inst=1000/(now-lastFrameMs);"
"      fpsAvg = fpsAvg ? (fpsAvg*0.8 + inst*0.2) : inst;"
"      fpsEl.textContent=fpsAvg.toFixed(1)+' Hz';"
"    }else{"
"      fpsEl.textContent='--- Hz';"
"    }"
"    lastFrameMs=now;"
"    const dv=new DataView(e.data);"
"    if(dv.byteLength<28)return;"
"    const ts=dv.getUint32(0,true);"
"    const age=dv.getUint32(4,true);"
"    const numSamplesFromHdr=dv.getUint32(8,true);"
"    const sps=dv.getUint32(12,true);"
"    const vmin=dv.getFloat32(16,true);"
"    const vmax=dv.getFloat32(20,true);"
"    const vavg=dv.getFloat32(24,true);"
"    const samplesOffset=28;"
"    const maxSamples=((dv.byteLength-samplesOffset)/2)|0;"
"    const numSamples=Math.min(numSamplesFromHdr,maxSamples);"
"    document.getElementById('sps').textContent=(sps/1000).toFixed(1)+'kSPS';"
"    document.getElementById('age').textContent=age+'ms';"
"    document.getElementById('vmin').textContent=vmin.toFixed(3)+'V';"
"    document.getElementById('vmax').textContent=vmax.toFixed(3)+'V';"
"    document.getElementById('vavg').textContent=vavg.toFixed(3)+'V';"
"    document.getElementById('vpp').textContent=(vmax-vmin).toFixed(3)+'V';"
"    ctx.fillStyle='#000';ctx.fillRect(0,0,canvas.width,canvas.height);"
"    ctx.strokeStyle='#0f0';ctx.lineWidth=1;ctx.beginPath();"
"    const W=canvas.width,H=canvas.height;"
"    for(let i=0;i<numSamples;i++){"
"      const raw=dv.getUint16(samplesOffset+i*2,true);"
"      const x=(i/(numSamples-1))*W;"
"      const y=H-(raw/4095)*H;"
"      i===0?ctx.moveTo(x,y):ctx.lineTo(x,y);"
"    }"
"    ctx.stroke();"
"  };"
"}"
"connect();"
// ADD THIS: Command sending function
"function sendCmd(cmd,value){"
"  if(ws&&ws.readyState===1){"
"    const msg=JSON.stringify({cmd:cmd,value:value});"
"    console.log('Sending:',msg);"
"    ws.send(msg);"
"  }"
"}"
// ADD THIS: Wire up controls
"document.getElementById('trigLevel').oninput=e=>{"
"  const v=parseFloat(e.target.value);"
"  document.getElementById('trigLevelVal').textContent=v.toFixed(2)+'V';"
"  sendCmd('trigger_level',v);"
"};"
"document.getElementById('trigMode').onchange=e=>sendCmd('trigger_mode',parseInt(e.target.value));"
"document.getElementById('trigEdge').onchange=e=>sendCmd('trigger_edge',parseInt(e.target.value));"
"document.getElementById('timeDiv').onchange=e=>sendCmd('timebase_scale',parseFloat(e.target.value));"
"document.getElementById('runStop').onclick=e=>{"
"  running=!running;"
"  sendCmd('run_stop',running?1:0);"
"  e.target.textContent=running?'STOP':'RUN';"
"};"
"</script></body></html>";

const size_t frontend_index_html_len = sizeof(frontend_index_html) - 1;